image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  before_script: 
    - npm i instantclient
    - npm i libaio
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

start_server:
  stage: build
  script:
    - node .


testing_a:
  stage: test
  script: npm test