image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build_and_start:
  stage: build
  before_script: 
    - npm i instantclient
    - npm i libaio
  script:
    - npm install
  after_script:
    - node .
  artifacts:
    paths:
      - node_modules/


testing_a:
  stage: test
  script: npm test