image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script: echo 'building'
  tags:
    - shopapp
    - windows


auto_test:
  stage: test
  script: npm test
  tags:
    - shopapp
    - windows


deploy_test:
  stage: deploy
  script: echo 'deploying on test'
  only:
    - test
  tags:
    - shopapp
    - windows
  
deploy_prod:
  stage: deploy
  script: echo 'deploying on prod'
  only:
    - prod
  tags:
    - shopapp
    - docker
    - secondary