image: node:latest

stages:
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

testing_a:
  stage: test
  script: npm test test/test.js
  tags:
    - shopapp
    - windows

testing_b:
  stage: test
  script: npm test test/other.test.js
  

build_app:
  stage: build
  script: echo 'build is done'

deploy_stage:
  stage: deploy
  script: echo 'deploying on stage'
  
  
deploy_prod:
  stage: deploy
  script: echo 'deploying on prod'
  when: manual