image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script: 
    - npm install
  except:
    - auth_feature
  artifacts:
    paths:
      - node_modules/
  tags:
    - shopapp
    - windows


auto_test_on_commit:
  stage: test
  script: npm test
  except:
    - auth_feature
  artifacts:
    paths:
      - node_modules/
  tags:
    - shopapp
    - windows

auto_test_on_merge:
  stage: test
  script: npm test
  only: merge_requests
  artifacts:
    paths:
      - node_modules/
  tags:
    - shopapp
    - windows


deploy_test:
  stage: deploy
  script: echo 'deploying on test'
  only:
    - test
  tags:
    - shopapp
    - windows
  
deploy_prod:
  stage: deploy
  script: echo 'deploying on prod'
  only:
    - prod
  tags:
    - shopapp
    - docker
    - secondary